### ISSUE TITLE
[BUG] Sound auto-play failing

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-enhanced-journal#361] opened 2022-09-01 03:13 UTC
![image](https://user-images.githubusercontent.com/99844555/187823803-1a181336-9ae0-439b-9619-3392ca27a726.png)

First message https://discord.com/channels/862414864692281386/862421185211924540/1014722043591282689

Sound is only intermittently playing on the player-side when opened/shown to them; and doesn't play again a second time.

Foundry 9.280
D&D 5e 
MEJ 1.0.65
FTC ✔️ 
Tested in Chrome & Firefox.

**Comment by nirurin** [comment] 2022-09-01 03:23
Just to add detail - 

I am opening the loot page for players by using the 'show players' dialogue.

The first time I do it for a loot page, the sound auto-plays as expected (unless the player has never interacted with the browser, in which case the above message pops up in console saying 'delaying until after first user gesture' which is fine.)

The problem is that, the second time I 'show' that loot page for players (I'm using the same loot page each time, as I need to in order to have a sound connected to it), the sound doesn't automatically play. There are no messages in the console that mention anything about sound for these attempts.

![Screenshot 2022-09-01 042323](https://user-images.githubusercontent.com/3751273/187825146-079a8c59-15d4-4f2e-9d94-495c6967565f.png)

**Comment by Crowguard** [comment] 2022-09-01 03:42
Small update, its also affecting Item Pile sounds that trigger on opening/closing.

**Comment by nirurin** [comment] 2022-09-01 03:51
> Small update, its also affecting Item Pile sounds that trigger on opening/closing.

But only when I use the corner X, or the 'leave' button, to exit the pile. Sounds will no longer play when I reopen the chest. 

UNLESS -- I then open the chest and close it with 'close lid'. Then when I reopen it, the sound plays as normal. 

So close lid works fine, but leave or X makes sounds stop working in the same way as enhanced journal. 

Except crowguard tried it, and it doesn't happen for him, so........ big shrug

**Comment by ironmonk88** [comment] 2022-12-29 22:35
I believe this has been fixed in the latest version.
Can someone confirm before I close the ticket?

**Comment by ironmonk88** [comment] 2023-01-08 22:08
Closing the ticket as I think it's been fixed.

**Closed by ironmonk88** 2023-01-08 22:08 UTC
Labels: question, fixed waiting release
