### ISSUE TITLE
Compatibility with GM Screen

### ISSUE THREAD

**Issue by Turqueso** [ironmonk88/monks-enhanced-journal#14] opened 2021-06-01 18:42 UTC
Is it possible to make it compatible with [GM Screen](https://github.com/ElfFriend-DnD/foundryvtt-gmScreen)?

**Comment by Turqueso** [comment] 2021-06-04 00:58
After using it a bit, it may be that GM screen is the one that should update.

**Comment by WereDev** [comment] 2021-07-14 01:26
Is the issue you're seeing similar to #51 ?

**Comment by Turqueso** [comment] 2021-07-14 02:30
For me, when I click on GM screen to open the full entry I get an empty window en only this warning
![imagen](https://user-images.githubusercontent.com/4932347/125548369-619e30e7-b1ca-4a87-a821-f727839d2af8.png)

**Comment by akrigline** [comment] 2021-07-14 15:54
Author of GM Screen here. I think there's going to be some heavy work on both our parts to get these modules compatible. Since we are both hacking around Foundry's expectation for a single JournalEntryConfig class, we both do things that probably cause incompatibility. I haven't had time to actually dig into this problem but it's a gnarly one from what I can see.

**Comment by ironmonk88** [comment] 2021-07-14 16:46
I think I may have figured the other issue out.  GM Screen was opening up a temp journal entry, and Enhanced Journal registered that as the "main" journal entry.  So when Enhanced Journal was asked to open for real, it assumed that the one GM Screen opened was the real deal.  I've added code to check the registered main journal entry and if it's not rendered, and not set to be rendered, then I switch over to using the one that's trying to open, rather than just taking it's content and putting it on the previously opened one.  Lol.  Hopefully that makes sense.  It works for GM Screen, I'm just checking to make sure it didn't break anything else.

I can't comment on the entity being deprecated though as I can't seem to reproduce it.  Which it's possible I may have fixed it already.

Also... awesome module by the way.

**Comment by Turqueso** [comment] 2021-07-15 01:40
I was able to open the entries! then... everything crashed. I get this error over en over like there an infinite loop somewhere when I activate the Journal
![imagen](https://user-images.githubusercontent.com/4932347/125714548-90323a9d-223a-4a49-a791-3c0e3ccf13ab.png)

**Comment by ironmonk88** [comment] 2021-07-15 06:18
That would be the error WereDev reported.
Should be fixed in the next release.

**Comment by ironmonk88** [comment] 2021-07-21 01:21
Should be fixed with the latest release.

**Closed by ironmonk88** 2021-07-21 01:21 UTC
Labels: fixed waiting release
