### ISSUE TITLE
[BUG] Currency Conversion from Price Adjustment

### ISSUE THREAD

**Issue by EnoEtile** [ironmonk88/monks-enhanced-journal#535] opened 2023-03-15 06:51 UTC
**Describe the bug**
When using the "adjust all prices" button to set prices to a percentage the values don't seem to translate between different currencies (gold, silver, copper, etc). For example if a player sells an item worth 1gp and the buyback adjustment is set at .75 the player gets 0gp. If they sell an item worth 2 gp they get 1 gp instead of the correct 1 gp and 5 silver. If a player sells an item of 100gp they get the correct 75gp. 

**To Reproduce**
1. Go to any shop journal entry (while using the default 5e currency values)
2. Adjust prices to buyback or sell to a decimal value (.5 or .75, etc).
3. Sell or buy an item with an adjusted price that would go between currencies
4. You will receive the wrong value

**Expected behavior**

**Screenshots**
![ClubValue](https://user-images.githubusercontent.com/127924153/225226888-27cf9205-3d85-4d8e-a209-2d608bfa5a81.JPG)
![PriceAdjustment](https://user-images.githubusercontent.com/127924153/225226890-5f33084a-c936-4add-b7ce-852dafe9ed9f.JPG)
![SellClubOffer](https://user-images.githubusercontent.com/127924153/225226896-eb29f03e-492c-457b-b025-734e041b0230.JPG)

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version Most Current Version
 - System D&D5e
 - Module version Monk's Enhanced Journal 10.14
 - Are there any errors in the console [e.g. press F12 and look for red text] No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Additional context**

**Comment by ironmonk88** [comment] 2023-03-15 07:47
Duplicate of #477

**Closed by ironmonk88** 2023-03-15 07:47 UTC
Labels: duplicate
