### ISSUE TITLE
[BUG] Content link matching when highlighted black background unreadable

### ISSUE THREAD

**Issue by CDormeyer** [ironmonk88/monks-enhanced-journal#691] opened 2024-04-10 16:02 UTC
**Describe the bug**
When using the enhanced journal addon, any highlighting results in a black box where the text is hard to read. 

**To Reproduce**
1. Write something
2. Highlight the text to use "Content link matching when highlighted"

**Expected behavior**
Not having the black background

**Screenshots**
See here how it should NOT be
![grafik](https://github.com/ironmonk88/monks-enhanced-journal/assets/74490169/dc542a92-e9ad-4e0c-963f-ff337c3aed54)

This is what it should look like 
![grafik](https://github.com/ironmonk88/monks-enhanced-journal/assets/74490169/f021e5d5-dcb6-455c-bdea-71c901fa0ca3)

**Please complete as much of the following information as possible:**
 - Foundry Version [v11 - b315]
 - System [Pathfinder 2e]
 - Module version 11.10
 - Are there any errors in the console: none
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Only installed and used this one module in a new world

**Comment by Crowguard** [comment] 2024-04-10 19:19
Duplicate of #663

**Comment by ironmonk88** [comment] 2024-05-04 23:56
Closing, duplicate of #663

**Closed by ironmonk88** 2024-05-04 23:56 UTC
Labels: duplicate
