### ISSUE TITLE
[BUG] Assigning a class does not work

### ISSUE THREAD

**Issue by thangurion** [ironmonk88/monks-enhanced-journal#438] opened 2022-11-21 08:04 UTC
When I want to add a class to a player character, it doesn't go on at step 2. 
A red box appears around the "next" button, but nothing else happens. 
If I disable the Enhanced Journal module, it works again.

DND: 2.03
Foundry: 10.290
Enhanced Journal: 10.5

![Error Enhanced Journal](https://user-images.githubusercontent.com/113504992/202995617-57619fb5-9244-458b-b007-7f0e91ad4aaf.png)

Greetings

**Comment by Amalica** [comment] 2022-11-21 17:41
I would like to Second this issues. After going through nearly every module this issue above was from this module. 

In addition, you can not open the items realted to class, subclass, or backgrounds. 

I'm only a month in and was really liking this module, i hope it gets fixed. Thanks.

**Comment by AntonioDeTeo** [comment] 2022-11-23 00:23
The latest update definitely breaks some things. I'm using Version 10 - Build 290 from Foundryvtt and the same thing happens to me. 
I was able to fix it by manually installing the previous version of this module. I recommend you do that while waiting for a new update.

**Comment by tigue54** [comment] 2022-11-23 06:48
I do the same and back in 10.3 waiting new update of this wonderful module

**Comment by ironmonk88** [comment] 2022-11-23 07:56
Closing, duplicate of #439.
Although... technically you posted this before that one... I just didn't connect the two until now.  But it's the same issue.

**Closed by ironmonk88** 2022-11-23 07:56 UTC
Labels: duplicate
