### ISSUE TITLE
[BUG] Cant open backgrounds with grant item when this module is active

### ISSUE THREAD

**Issue by BladeFireLight** [ironmonk88/monks-enhanced-journal#441] opened 2022-11-22 01:09 UTC
**Describe the bug**
Backgrounds have the option to given items (weapons, spells, features) on multiple levels. if a background has any. it fails to open for viewing or editing if MEJ is loaded. 

**To Reproduce**
1. enable MEJ
2. create a new Item of type Background
3. select advancement tab
4. click +
5. select Grant Items, and click create
6. Drag item into list
7. close item grant page 
8. close background
9. try to open the background again

**Expected behavior**
Once Items are added they should still be modifiable

**Screenshots**
error from f12
ypeError: Cannot destructure property 'async' of 'options' as it is undefined.
[Detected 3 packages: monks-enhanced-journal, lib-wrapper, system:dnd5e]
    at TextEditor.createContentLink (monks-enhanced-journal.js:1068:19)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at TextEditor._lw_TextEditor__createContentLink (PatcherTextEditor.js:146:16)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁TextEditor._createContentLink#0 (libWrapper-wrapper.js:189:20)
    at Object.linkForUuid (utils.mjs:79:21)
    at item-grant.mjs:55:86
    at Array.reduce (<anonymous>)
    at ItemGrantAdvancement.summaryForLevel (item-grant.mjs:55:44)
    at item-sheet.mjs:165:30
    at Array.map (<anonymous>)
    at ItemSheet5e._getItemAdvancement (item-sheet.mjs:159:34)
    at ItemSheet5e.getData (item-sheet.mjs:101:25)
    at async ItemSheet5e._render (foundry.js:5067:18)
    at async ItemSheet5e._render (foundry.js:5780:5)

**Please complete as much of the following information as possible:**
 - Browser Edge Chromium 07.0.1418.52
 - Foundry Version v10.209
 - System D&D5e
 - Module version 10.5
 - Are there any errors in the console Pasted above
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. That is how I found it was this one. 

**Additional context**
I think this was just introduced in the last release of MEJ

**Comment by BladeFireLight** [comment] 2022-11-22 01:12
f12 error with just MEJ active
foundry.js:747 
        
       TypeError: An error occurred while rendering ItemSheet5e 69. Cannot destructure property 'async' of 'options' as it is undefined.
    at TextEditor.createContentLink (monks-enhanced-journal.js:1068:19)
    at TextEditor._createContentLink (monks-enhanced-journal.js:1120:42)
    at Object.linkForUuid (utils.mjs:79:21)
    at item-grant.mjs:55:86
    at Array.reduce (<anonymous>)
    at ItemGrantAdvancement.summaryForLevel (item-grant.mjs:55:44)
    at item-sheet.mjs:165:30
    at Array.map (<anonymous>)
    at ItemSheet5e._getItemAdvancement (item-sheet.mjs:159:34)
    at ItemSheet5e.getData (item-sheet.mjs:101:25)

**Comment by ironmonk88** [comment] 2022-11-23 07:47
Closing duplicate of #439

**Closed by ironmonk88** 2022-11-23 07:47 UTC
Labels: duplicate
