### ISSUE TITLE
PF2 Crit/Fumble deck cant be read 

### ISSUE THREAD

**Issue by Walzerian** [ironmonk88/monks-enhanced-journal#627] opened 2023-09-21 11:55 UTC
**Describe the bug**
When MEJ is active there is almost impossible to read the Crit/fumbledeck in PF2e

![image](https://github.com/ironmonk88/monks-enhanced-journal/assets/63548862/cf783bcd-1f26-45fb-8fa5-8eb1bb2274b1)

**Comment by ironmonk88** [comment] 2023-10-10 04:47
duplicate of #618 
Closing this one... although I like that you included an image.  That made it easier to track down.

**Closed by ironmonk88** 2023-10-10 04:47 UTC
Labels: duplicate, fixed waiting release
