### ISSUE TITLE
un-intended feature?? Character sheet in journal

### ISSUE THREAD

**Issue by mesoraven** [ironmonk88/monks-enhanced-journal#49] opened 2021-07-12 20:56 UTC
hey, forst of all love you mod very useful i found out you can put a character sheet directly into the journal tabs without a person journal entry. i cant see it written anyway did you know that worked?

https://user-images.githubusercontent.com/86850322/125354617-eba63700-e35b-11eb-9c00-58f74d816f8d.mp4

**Comment by ironmonk88** [comment] 2021-07-12 21:17
100% intended.  It's so you can set up a combat with your encounter on one tab and a tab for all the enemies your players might face.
It's listed at the very bottom of all the entries that are available.  "Actor Entry"  It's not one that you can create though because the Journal isn't a place for creating an Actor.
It works reasonably well, but has issues in systems other than DnD5e.

**Comment by ironmonk88** [comment] 2021-07-21 01:23
closing this because it's working as intended.

**Closed by ironmonk88** 2021-07-21 01:23 UTC
