### ISSUE TITLE
[Request/Issue] Game system icons are bypassed 

### ISSUE THREAD

**Issue by Gardakan93** [ironmonk88/monks-enhanced-journal#199] opened 2022-02-08 11:29 UTC
Hi ! 

Special characters provided by some game system, like dice symbol in FFG systems are override by the module. 
If the journal entry was created without the module, the module keep displaying theses icons, but if we edit the journal entry or try to create a new one with special characters, it won't recognize it.

Is it possible to fix ? 

Thank you for your great work !

**Comment by ironmonk88** [comment] 2022-03-12 05:35
Can you show me a screen shot of how you get the special characters?

**Comment by Gardakan93** [comment] 2022-03-15 14:22
Here is a screenshot of L5R special characters syntaxe with your module (icon doesn't appear)
![image](https://user-images.githubusercontent.com/23028455/158397370-eed13c95-e244-4c1f-90f1-a659b67e5141.png)

Here is a screenshot of the same characters without your module (wich display icons)
![image](https://user-images.githubusercontent.com/23028455/158397945-70a9f7f3-effd-42c5-be57-93803e46f6de.png)

You can find on the french wiki of L5R for foundry the detail of all special characters. Here's a screenshot :
![image](https://user-images.githubusercontent.com/23028455/158398395-17dacd13-c3eb-4f27-ba1f-206da207123b.png)

This is similar to special characters for star wars ffg system (which works with your module).

**Comment by ironmonk88** [comment] 2022-04-10 23:53
Okay, I've looked into this extensively..., and... I don't think I can fix it.  At least not easily.
The problem is, that L5R is using a really weird way to try and add these symbols, by converting to text before editing, and then back on saving.
Core Foundry uses a function called enrichHTML which is used to add symbols like this that doesn't affect the saving of the text.  I think this should really go back to the developers of the system to use the Foundry method for displaying the symbols instead.  It would avoid confusion and would be a little more stable than what they're currently using.
That's just my opinion... but for me to make it work I'd have to jump through a lot of hoops.
If you contact them and they absolutely refuse to do it that way... please let me know and I'll revisit this and try and put something together.

**Comment by ironmonk88** [comment] 2022-12-30 00:10
Closing this as it seems to be working now.

**Closed by ironmonk88** 2022-12-30 00:10 UTC
Labels: question
