### ISSUE TITLE
[BUG] No scrollbar for location or organization journals

### ISSUE THREAD

**Issue by dreamaway00** [ironmonk88/monks-enhanced-journal#430] opened 2022-11-11 23:59 UTC
**Describe the bug**
There is no scrollbar for location or organization type journals. Normal journals seem to work as intended. This cuts off information at the bottom of the screen. The only way to see the rest of the information is to expand the journal entry to as big as it can go, but if there is more information then it is cut off. There IS a scrollbar for the list to the right, just not the information in the entry.

**To Reproduce**
No steps, just always occurs.

**Expected behavior**
Use of scrollbar.

**Screenshots**
[x](https://gyazo.com/e5c00f6f4e98a0d304e5d4776e629d0f)
[x](https://gyazo.com/902726ef08a87a025b9557a5dd48ef11)

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version v10, hosted on Forge
 - 5e 2.0.3
 - MEJ 10.4
 - No red errors in the console

**Comment by ironmonk88** [comment] 2022-11-19 06:43
Closing as it's a duplicate of #420

**Closed by ironmonk88** 2022-11-19 06:43 UTC
Labels: duplicate
