### ISSUE TITLE
[BUG]Enter Causes Reset on Stock Journal Title Edit

### ISSUE THREAD

**Issue by Lyinggod** [ironmonk88/monks-enhanced-journal#538] opened 2023-03-25 14:15 UTC
**Describe the bug**
Editing the title of a stock journal causes page to reset when ENTER is pressed after making the edit. The right sidebar becomes detached from the bottom and changes size based on its content. A port of the web page/address (in Forge) becomes the name of the journal edited, such as "username.forge-vtt.com/game?name=Session+ZERO" where "Session Zero" is the new name of the stock journal.

**To Reproduce**
1. Create a stock (Non-MEJ) journal
2. Edit stock journal name, press Enter. Note: appears to work as expected if ENTER is not pressed and journal is "clicked off of"
3. Making other edits to journal pior to pressing enter does not appear to cause the restart.

**Expected behavior**
After pressing enter, the stock journal name edit is applied but nothing resets.  Plus not altering the page.

**Please complete as much of the following information as possible:**
 - Browser: Chrome and Firefox in Forge + Foundry Client
 - Foundry Version: v10.291
 - System: Starfinder, Fate, FFG Star Wars, Genesys (Alpha)
 - Module version: 10.14
 - There appears to be no errors but screen resets almost instantly so this is hard to see
 - This occurs even if MEJ is the only module installed.

I went back to v10.1 of MEJ and found the problem was still present. Additionally, this is not

**Comment by Crowguard** [comment] 2023-05-22 16:59
Duplicate of #479

**Comment by ironmonk88** [comment] 2023-05-23 02:36
Closing as it's a duplicate of #479

**Closed by ironmonk88** 2023-05-23 02:36 UTC
Labels: duplicate
