### ISSUE TITLE
[BUG] "Place" journal image bug

### ISSUE THREAD

**Issue by pereiraoc** [ironmonk88/monks-enhanced-journal#425] opened 2022-11-04 12:55 UTC
Hello!

I've found a bug in the "Places" journals. It seems that the image is constantly enlarged (just like when you press on it).
I tried to create a new world and it seems the problem persists even this module is the only active one.

The module, system (pf2e) and foundry are all updated to the latest version. (04/nov/2022)

![image](https://user-images.githubusercontent.com/18019220/199976805-29fb6564-025d-4a4d-8343-196142d0f711.png)

Below is the json file of the journal I've created to test this bug.

```{
  "name": "test",
  "flags": {
    "monks-enhanced-journal": {
      "type": "place"
    },
    "exportSource": {
      "world": "pathfinder-2e-vanilla",
      "system": "pf2e",
      "coreVersion": "10.288",
      "systemVersion": "4.3.3"
    }
  },
  "pages": [
    {
      "type": "text",
      "name": "test",
      "flags": {
        "monks-enhanced-journal": {
          "type": "place",
          "attributes": {
            "age": {
              "value": ""
            },
            "size": {
              "value": ""
            },
            "government": {
              "value": ""
            },
            "alignment": {
              "value": ""
            },
            "faction": {
              "value": ""
            },
            "inhabitants": {
              "value": ""
            },
            "districts": {
              "value": ""
            },
            "agricultural": {
              "value": ""
            },
            "cultural": {
              "value": ""
            },
            "educational": {
              "value": ""
            },
            "indistrial": {
              "value": ""
            },
            "mercantile": {
              "value": ""
            },
            "military": {
              "value": ""
            }
          },
          "relationships": [],
          "placetype": "",
          "location": "",
          "SZAgcLKx0eRHciLt": {
            "notes": ""
          },
          "appendix": false,
          "scrollPos": "{\".tab.entry-details .tab-inner\":0,\".tab.townsfolk .tab-inner\":0,\".tab.shops .tab-inner\":0,\".tab.description .tab-inner\":0}"
        }
      },
      "_id": "OcyNlEchFbzirfhe",
      "title": {
        "show": true,
        "level": 1
      },
      "image": {},
      "text": {
        "format": 1
      },
      "video": {
        "controls": true,
        "volume": 0.5
      },
      "src": "Etrans-Folly-Gazetteer.webp",
      "system": {},
      "sort": 0,
      "ownership": {
        "default": -1
      }
    }
  ],
  "_stats": {
    "systemId": "pf2e",
    "systemVersion": "4.3.3",
    "coreVersion": "10.288",
    "createdTime": 1667566210215,
    "modifiedTime": 1667566210215,
    "lastModifiedBy": "SZAgcLKx0eRHciLt"
  }
}```

**Comment by pereiraoc** [comment] 2022-11-04 19:25
Just saw that someone already reported it in https://github.com/ironmonk88/monks-enhanced-journal/issues/420

**Comment by ironmonk88** [comment] 2022-11-19 06:42
Closing as it's a duplicate of #420

**Closed by ironmonk88** 2022-11-19 06:42 UTC
Labels: duplicate
