### ISSUE TITLE
[BUG] Error message on load

### ISSUE THREAD

**Issue by Aezrel** [ironmonk88/monks-enhanced-journal#494] opened 2023-01-31 23:19 UTC
**Describe the bug**
Loading into the world, an error message pops up - Monk's Enhanced Journal: Error detected in module (see JS console). Everything still "works" but whenever I try to open a journal entry or do anything in the journal tab (like delete an entry, edit, move, etc) it becomes extremely slow to the point of becoming unusable.

**To Reproduce**
1. Activate Monk's Enhanced Journal and libWrapper
2. Reload Foundry, error message should appear
3. Open a journal entry

**Expected behavior**
Journal entries behave normally and I can change pages, make edits, etc. without the entire system slowing to a crawl

**Screenshots**
![image](https://user-images.githubusercontent.com/97117980/215904737-bbcad407-23c4-46b0-904e-c978c8986a02.png)
![image](https://user-images.githubusercontent.com/97117980/215904826-50a00285-2f2b-48c1-ba98-2c14af441621.png)

**Please complete as much of the following information as possible:**
 - Browser: Chrome (up to date)
 - Foundry Version: 10.288 self-hosted on Ubuntu Server 22.04
 - System: D&D 5e 2.1.2
 - Module version: Monk's Enhanced Journal v10.12 & libWrapper v1.12.12.0
 - Are there any errors in the console: Yes, see screenshots above
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: 
 I did. it tells me libWrapper is the culprit, but the console message says it isn't a libWrapper error

**Additional context**
I tried uninstalling and reinstalling the module, launching in safe configuration, restarting Foundry, running Find The Culprit, all the troubleshooting steps I could think of, I can't find anything else that might be causing this.

**Comment by ironmonk88** [comment] 2023-02-05 06:11
duplicate of #487

**Closed by ironmonk88** 2023-02-05 06:11 UTC
Labels: duplicate, fixed waiting release
