### ISSUE TITLE
[Feature Request] Custom Currency

### ISSUE THREAD

**Issue by slave2midna** [ironmonk88/monks-enhanced-journal#642] opened 2023-11-21 19:49 UTC
**Is your feature request related to a problem? Please describe.**
Unable to define custom/system agnostic currency.

**Describe the solution you'd like**
Would like when setting up system currency, to be able to input my own path for custom currencies to allow use with the shop system.

**Comment by ironmonk88** [comment] 2023-11-25 18:28
duplicate of #532

**Closed by ironmonk88** 2023-11-25 18:28 UTC
Labels: duplicate, enhancement
