### ISSUE TITLE
Clicking a Journal link opens in same tab

### ISSUE THREAD

**Issue by SolarisDevorak** [ironmonk88/monks-enhanced-journal#164] opened 2022-01-06 21:24 UTC
I am not sure if this by design, looked for a setting but didn't see one. When clicking any journal link, it will open it in the same tab vs opening a new tab.

> "You can open multiple journal entries in Enhanced Journal by clicking on the + button to the right of the tabs. Once a new tab is open, clicking on items in the Journal Directory will open that entry in the new tab."

This method doesn't seem to work either. I can open a recently opened page on the new tab page, but this requires opening the link on the first tab, clicking back, going to the new tab and clicking the recently opened page.

**Comment by ironmonk88** [comment] 2022-01-09 04:49
That's pretty much by design.
Hold down the Ctrl key to open in a new tab.
Or Alt to open outside of the browser.

**Comment by ironmonk88** [comment] 2022-03-12 21:50
Closing this as it's working as designed.
There is also now a setting that you can turn on to open everything in a new tab instead of in the same tab.

**Closed by ironmonk88** 2022-03-12 21:50 UTC
