### ISSUE TITLE
[Feature Request] Close Tabs Context Menu

### ISSUE THREAD

**Issue by jlcanale** [ironmonk88/monks-enhanced-journal#563] opened 2023-05-23 20:32 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes while preparing for a session I wind up with dozens of tabs open as I browse around to different journal entries in my game, and I have to manually close each of them just to clean up the clutter.

**Describe the solution you'd like**
It would be great if we had a right-click context menu similar to browsers that let you do some combination of the following:
- Close all tabs
- Close all other tabs
- Close all tabs left of this
- Close all tabs right of this

**Comment by Crowguard** [comment] 2023-05-28 17:46
Duplicate of #519

**Comment by ironmonk88** [comment] 2023-08-07 02:30
Fixed in the latest release

**Closed by ironmonk88** 2023-08-07 02:30 UTC
Labels: enhancement, fixed waiting release
