### ISSUE TITLE
[BUG] Links on the Relationships tab won't work

### ISSUE THREAD

**Issue by theczarek** [ironmonk88/monks-enhanced-journal#549] opened 2023-04-07 10:39 UTC
**Describe the bug**
Links on the Relationships tab won't work

**To Reproduce**
1. Go to 'any entity with  Relationships  tab', add relationship by draging and droping another entity
2. Click on ' any relationship name on the list'

**Expected behavior**
On click on relationship name journal should open page for that relationshp entity

**Screenshots**
Following error appears on console
![image](https://user-images.githubusercontent.com/83540404/230593303-c52adc4e-0b17-4535-9c14-b66e15dd2167.png)

**Please complete as much of the following information as possible:**
 - Browser Chrome 112.0.5615.50
 - Foundry Version 10 build 921
 - System [CoC, DnD5e, City of Mist]
 - Module version 10.14
 - Are there any errors in the console [e.g. press F12 and look for red text]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. 
 - Yes, error repeats after deactivation of all oter modules

**Additional context**

**Comment by weepingminotaur** [comment] 2023-04-07 17:58
This is a known issue with an existing github ticket: https://github.com/ironmonk88/monks-enhanced-journal/issues/539

**Comment by ironmonk88** [comment] 2023-05-21 18:07
Duplicate of #539

**Closed by ironmonk88** 2023-05-21 18:07 UTC
Labels: duplicate
