### ISSUE TITLE
Linking to Character Sheets Opens Journal

### ISSUE THREAD

**Issue by SolarisDevorak** [ironmonk88/monks-enhanced-journal#159] opened 2021-12-31 19:12 UTC
When dragging and dropping a character sheet into a journal entry, the link is made and appears as a character link. But when clicking on the link, it opens the character sheet in a journal window instead of opening the sheet. The sheet is also blank, but this may be due to a module that is effecting the sheet theme (TidySheet)

**Comment by ironmonk88** [comment] 2022-01-01 23:43
That's by design.
Hold down the Alt key when clicking to open it as a sheet.
Or change the setting to open them as their own sheet.
![image](https://user-images.githubusercontent.com/75920956/147862414-de268a8d-69d2-4501-a447-31d19018bfd5.png)

The sheet being blank is a v9 issue and should be fixed in the next release.  Thank you for finding that.

**Comment by SolarisDevorak** [comment] 2022-01-06 21:17
Opening in a new window worked. Looking forward to the opening in journal blank issue! Thanks for a wonderful module!

**Comment by ironmonk88** [comment] 2022-01-31 05:21
Should be fixed in the latest release.

**Closed by ironmonk88** 2022-01-31 05:21 UTC
Labels: fixed waiting release
