### ISSUE TITLE
Players don't receive items from the shop and loot when using the new 5e character sheet.

### ISSUE THREAD

**Issue by Awan1996** [ironmonk88/monks-enhanced-journal#667] opened 2024-02-12 05:38 UTC
**Describe the bug**
Players don't receive items from the shop and loot when using the new 5e character sheet. It works just fine if they switch back to the legacy sheet.

**To Reproduce**
Use the new 5e character sheets.
Take an item from loot or buy and item from a shop

**Expected behavior**
The item should transfer to the player's inventory

**Please complete as much of the following information as possible:**
 - Foundry Version 11.315
 - System 5e 3.0.1
 - Module version 11.09

**Comment by Faellatv** [comment] 2024-02-12 09:35
Was searching because I have the same problem with exact same specs.
I can confirm lecacy sheet works fine.

**Comment by ironmonk88** [comment] 2024-05-05 20:14
Should be fixed in the latest version

**Closed by ironmonk88** 2024-05-05 20:14 UTC
Labels: fixed waiting release
